### PR TITLE
Update questionmarks

### PR DESCRIPTION
**Pull request by PaulJonasJost**
- Adjusted all links in the questionmarks
- Shortened Heatma, Preprocess and Sample Corr
- Updated Documentation of PreProcessing

### CODE REVIEW

**Comment by PaulJonasJost** [comment]
closes #387 
partially adresses #365 and #390

**Comment by PaulJonasJost** [comment]
now closes #390

**Comment by PaulJonasJost** [comment]
now should also close #365

**Review by LeaSeep — APPROVED** [review]
Thank you!

**Pull request merged**
